---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: podinfo
  name: podinfo
  namespace: demo
spec:
  rules:
  - host: podinfo.34.76.2.172.nip.io
    http:
      paths:
      - backend:
          serviceName: podinfo
          servicePort: 9898
        path: /
