apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: demo
spec:
  rules:
  - host: podinfo.34.76.2.172.nip.io
    http:
      paths:
      - backend:
          serviceName: podinfo
          servicePort: 9898
        path: /
